modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/starfish-studios/AnotherFurniture/issues"

[[mods]]
modId = "another_furniture"
version = "${version}"
displayName = "Another Furniture"
#updateJSONURL="http://myurl.me/"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/another-furniture"
logoFile = "icon.png"
#credits="Thanks for this example mod goes to Java"
authors = "Starfish Studios"
description = '''
Decorating your home just got better! Another Furniture adds various furniture, with the goal of staying vanilla-styled and consistently sized, keeping normal blocks and player sizes in mind.
'''

[[dependencies.another_furniture]]
modId = "forge"
mandatory = true
versionRange = "[47.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.another_furniture]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
